Update update.yaml

diff --git a/.github/workflows/update.yaml b/.github/workflows/update.yaml
--- a/.github/workflows/update.yaml
+++ b/.github/workflows/update.yaml
@@ -2,7 +2,7 @@ name: Update subscriptions
 
 on:
   schedule:
-    - cron: "0 */23 * * *"  # 每6小时运行一次
+    - cron: "0 */23 * * *"  # Setiap 23 jam
   workflow_dispatch:
 
 jobs:
@@ -19,10 +19,20 @@ jobs:
           python-version: '3.10'
 
       - name: Install dependencies
-        run: pip install requests pyyaml speedtest-cli aiohttp tqdm v2ray
+        run: pip install requests pyyaml speedtest-cli aiohttp tqdm
+
+      - name: Install V2Ray
+        run: |
+          wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-linux-64.zip
+          unzip v2ray-linux-64.zip
+          sudo mv v2ray /usr/local/bin/
+          sudo mv v2ctl /usr/local/bin/
+          sudo chmod +x /usr/local/bin/v2ray
+          sudo chmod +x /usr/local/bin/v2ctl
 
       - name: Run Python script
-        run: python3 main.py
+        run: |
+          python3 main.py || { echo "Script failed"; exit 1; }
 
       - name: Push changes
         run: |
